### ISSUE TITLE
panic while running autoplay

### ISSUE THREAD

**Issue by domino14** [domino14/macondo#159]
```
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x125fb09]


goroutine 25 [running]:
runtime.throw({0x146031b, 0x13d84e0})
        runtime/panic.go:1198 +0x71 fp=0xc0000d38c8 sp=0xc0000d3898 pc=0x1034db1
runtime.sigpanic()
        runtime/signal_unix.go:742 +0x2f6 fp=0xc0000d3918 sp=0xc0000d38c8 pc=0x104a536
github.com/domino14/macondo/strategy.(*OldLeaves).LeaveValue(0xc0000da3f0, {0x4000000000000000, 0xc0000da310, 0x6a})
        github.com/domino14/macondo/strategy/read_olv.go:43 +0x1e9 fp=0xc0000d3958 sp=0xc0000d3918 pc=0x125fb09
github.com/domino14/macondo/strategy.ExhaustiveLeaveStrategy.LeaveValue(...)
        github.com/domino14/macondo/strategy/exhaustive_leave.go:118
github.com/domino14/macondo/strategy.ExhaustiveLeaveStrategy.Equity({{0x14ee140, 0xc0000da3f0}, {0x1812090, 0x0, 0x0}}, 0xc003faa5a0, 0x0, 0xc0000ca050, 0x0)
        github.com/domino14/macondo/strategy/exhaustive_leave.go:102 +0x107 fp=0xc0000d39e0 sp=0xc0000d3958 pc=0x125ed67
github.com/domino14/macondo/strategy.(*ExhaustiveLeaveStrategy).Equity(0xc00007a1e0, 0xf, 0x2000000033, 0x3ffffffffffff, 0x3ffffffffffff)
        <autogenerated>:1 +0x86 fp=0xc0000d3a60 sp=0xc0000d39e0 pc=0x1260466
github.com/domino14/macondo/ai/player.(*RawEquityPlayer).AssignEquity(0xc0000a6228, {0xc00424c000, 0x906, 0xc0000d3b10}, 0x104f489, 0xc0000d3b10, 0x0)
        github.com/domino14/macondo/ai/player/player.go:59 +0x65 fp=0xc0000d3ac0 sp=0xc0000d3a60 pc=0x12625e5
github.com/domino14/macondo/ai/runner.GenerateMoves(0xc0002381e0, {0x14fa8f8, 0xc0000a6228}, {0x14f59d0, 0xc0000da310}, 0x0, 0x1)
        github.com/domino14/macondo/ai/runner/runner.go:107 +0x15d fp=0xc0000d3b78 sp=0xc0000d3ac0 pc=0x126563d
github.com/domino14/macondo/automatic.(*GameRunner).genBestMoveForBot(...)
        github.com/domino14/macondo/automatic/game_runner.go:125
github.com/domino14/macondo/automatic.(*GameRunner).PlayBestStaticTurn(0xc0000d3f28, 0x1)
        github.com/domino14/macondo/automatic/game_runner.go:132 +0x6e fp=0xc0000d3d20 sp=0xc0000d3b78 pc=0x137b94e
github.com/domino14/macondo/automatic.(*GameRunner).playFullStatic(0xc0000d3f28)
        github.com/domino14/macondo/automatic/automatic_utils.go:48 +0xd0 fp=0xc0000d3e50 sp=0xc0000d3d20 pc=0x1379530
github.com/domino14/macondo/automatic.StartCompVCompStaticGames.func1(0x0)
        github.com/domino14/macondo/automatic/automatic_utils.go:117 +0x2a5 fp=0xc0000d3fc8 sp=0xc0000d3e50 pc=0x137af85
github.com/domino14/macondo/automatic.StartCompVCompStaticGames·dwrap·1()
        github.com/domino14/macondo/automatic/automatic_utils.go:121 +0x2d fp=0xc0000d3fe0 sp=0xc0000d3fc8 pc=0x137acad
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc0000d3fe8 sp=0xc0000d3fe0 pc=0x1064e01
created by github.com/domino14/macondo/automatic.StartCompVCompStaticGames
        github.com/domino14/macondo/automatic/automatic_utils.go:105 +0x4a5
```

```go

func (olv *OldLeaves) LeaveValue(leave alphabet.MachineWord) float64 {
	ll := len(leave)
	for i := 1; i < ll; i++ {
		for j := i; j > 0 && leave[j-1] > leave[j]; j-- {             // THIS IS THE CRASH LINE
			leave[j-1], leave[j] = leave[j], leave[j-1]
		}
	}
```

**Comment by domino14** [comment]
`0xb01dfacedebac1e` is a google-able address. this seems to be a rare thing that could not be reproduced. could be my old bad computer
