### ISSUE TITLE
sim details seems to only show two plies worth of data

### ISSUE THREAD

**Issue by domino14** [domino14/macondo#214]

**Comment by domino14** [comment]
actually `sim 14` can crash:

```
macondo> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x68576a]

goroutine 282 [running]:
github.com/domino14/macondo/game.(*Game).handleConsecutiveScorelessTurns(0xc0022849a0, 0x0)
	github.com/domino14/macondo/game/game.go:587 +0x4a
github.com/domino14/macondo/game.(*Game).PlayMove(0xc0022849a0, 0xc0001d7dc0, 0x0, 0x0)
	github.com/domino14/macondo/game/game.go:551 +0x545
github.com/domino14/macondo/montecarlo.(*Simmer).simSingleIteration(0xc000174240, 0xe, 0x7, 0x24, 0x40f2dd?)
	github.com/domino14/macondo/montecarlo/montecarlo.go:424 +0x6e5
github.com/domino14/macondo/montecarlo.(*Simmer).Simulate.func4()
	github.com/domino14/macondo/montecarlo/montecarlo.go:349 +0x191
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:54 +0x8d
```

**Comment by ddugovic** [comment]
I see, this stack trace must have been observed from the `board-refactor` branch...

https://github.com/domino14/macondo/blob/577c04b77d6affe71788950616fe3ef282d438b2/game/game.go#L582-L587
