### ISSUE TITLE
sim crashes

### ISSUE THREAD

**Issue by domino14** [domino14/macondo#68]
```
macondo> rack AEFIOST

   A B C D E F G H I J K L M N O                      úrsula           371
   ------------------------------    ->              arcadio  AEFIOST  344
 1|J I N '       =       '     =
 2|  O A R I E S T   "       -      Bag + unseen: (8)
 3|    - E   E U O I       -
 4|'     T     s W O L E S T   '    A D E I N O V Z
 5|      I -           B
 6|  "   N   "       M O     "
 7|    ' A     '   Q I N   G
 8|=     E       V A X   G U L P
 9|    '       '   D       A
10|  T H R A W N   I F     r "      Turn 20:
11|        L O U P   L -   I        arcadio played 1A JIN for 34 pts from a ra
12|N E E M B   T U Y E R E S   '    ck of IJN
13|    -       ' K ' G     H
14|  A C C O R D E D "       -
15|=     '       Y A R R '     =

macondo> gen
     Move                Leave  Score Equity

  1: 1H SOFTIE           A      51    52.09
  2: 1H SOFTA            EI     48    48.93
  3: 1H SOFA             EIT    42    45.35
  4: K10 FA.O            EIST   30    44.28
  5: 1H SEIF             AOT    42    41.89
  6: 1H SAFE             IOT    42    41.26
  7: 1H SOFT             AEI    42    41.18
  8: K10 FO.             AEIST  25    40.13
  9: 1H STOAI            EF     39    38.99
 10: 1H SAFT             EIO    42    38.69
 11: 1H SIFT             AEO    42    38.68
 12: 1H SIF              AEOT   39    38.49
 13: 1H STOAE            FI     39    37.75
 14: C5 OAF              EIST   23    37.28
 15: E4 OF               AEIST  22    37.13
macondo> sim
Simulation started. Please do `sim show` and `sim details` to see more info
macondo> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xdc pc=0x13fe5cd]

goroutine 15 [running]:
github.com/domino14/macondo/game.(*Game).PlayMove(0xc000536780, 0xc0003b8f00, 0xc0000fc100, 0x0, 0xc000098570, 0x0)
	/Users/cesar/code/macondo/game/game.go:355 +0x20d
github.com/domino14/macondo/montecarlo.(*Simmer).simSingleIteration(0xc0000be8c0, 0x2, 0x2, 0x1, 0xc00008e900)
	/Users/cesar/code/macondo/montecarlo/montecarlo.go:340 +0x224
github.com/domino14/macondo/montecarlo.(*Simmer).Simulate.func4(0x0, 0x0)
	/Users/cesar/code/macondo/montecarlo/montecarlo.go:264 +0x1aa
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000137bf0, 0xc000137c80)
	/Users/cesar/go/pkg/mod/golang.org/x/sync@v0.0.0-20200317015054-43a5402ce75a/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/cesar/go/pkg/mod/golang.org/x/sync@v0.0.0-20200317015054-43a5402ce75a/errgroup/errgroup.go:54 +0x66
```

**Comment by domino14** [comment]
fixed
